pickable:
  easy:
    - minecraft:stone_sword
    - minecraft:stone_shovel
    - minecraft:stone_pickaxe
    - minecraft:stone_axe
    - minecraft:stone_hoe
    - minecraft:flint
    - minecraft:coal
    - minecraft:beef
    - minecraft:cooked_beef
  medium:
    - minecraft:iron_ingot
    - minecraft:gold_ingot
    - minecraft:feather
    - minecraft:leather
    - minecraft:string
    - minecraft:paper
    - minecraft:gunpowder
    - minecraft:red_dye
    - minecraft:yellow_dye
    - minecraft:blue_dye
    - minecraft:black_dye
    - minecraft:white_dye
  hard:
    - minecraft:yellow_banner
    - minecraft:pink_banner
    - minecraft:gray_banner
    - minecraft:light_gray_banner
    - minecraft:cyan_banner
    - minecraft:purple_banner
    - minecraft:blue_banner
    - minecraft:green_banner
    - minecraft:red_banner
    - minecraft:black_banner
    - minecraft:egg
craftable:
  easy:
    - minecraft:oak
    - minecraft:stone_sword
    - minecraft:stone_shovel
    - minecraft:stone_pickaxe
    - minecraft:stone_axe
    - minecraft:stone_hoe
    - minecraft:furnace
    - minecraft:chest
  medium:
    - minecraft:iron_helmet
    - minecraft:iron_chestplate
    - minecraft:iron_leggings
    - minecraft:iron_boots
    - minecraft:iron_hoe
    - minecraft:iron_sword
    - minecraft:iron_pickaxe
    - minecraft:iron_axe
    - minecraft:leather_horse_armor
    - minecraft:iron_block
    - minecraft:gold_block
  hard:
    - minecraft:enchanting_table
    - minecraft:bookshelf
    - minecraft:golden_helmet
    - minecraft:golden_chestplate
    - minecraft:golden_leggings
    - minecraft:golden_boots
    - minecraft:tnt
    - minecraft:deepslate_brick_stairs

# Other existing items
#
# minecraft:diamond
# minecraft:gold_ingot
# minecraft:iron_sword
# minecraft:diamond_sword
# minecraft:diamond_shovel
# minecraft:diamond_pickaxe
# minecraft:diamond_axe
# minecraft:stick
# minecraft:bowl
# minecraft:mushroom_stew
# minecraft:golden_sword
# minecraft:golden_shovel
# minecraft:golden_pickaxe
# minecraft:golden_axe
# minecraft:wooden_hoe
# minecraft:iron_hoe
# minecraft:diamond_hoe
# minecraft:golden_hoe
# minecraft:wheat_seeds
# minecraft:wheat
# minecraft:bread
# minecraft:leather_helmet
# minecraft:leather_chestplate
# minecraft:leather_leggings
# minecraft:leather_boots
# minecraft:chainmail_helmet
# minecraft:chainmail_chestplate
# minecraft:chainmail_leggings
# minecraft:chainmail_boots
# minecraft:iron_helmet
# minecraft:iron_chestplate
# minecraft:iron_leggings
# minecraft:iron_boots
# minecraft:diamond_helmet
# minecraft:diamond_chestplate
# minecraft:diamond_leggings
# minecraft:diamond_boots
# minecraft:porkchop
# minecraft:cooked_porkchop
# minecraft:painting
# minecraft:golden_apple
# minecraft:enchanted_golden_apple
# minecraft:sign
# minecraft:bucket
# minecraft:water_bucket
# minecraft:lava_bucket
# minecraft:minecart
# minecraft:saddle
# minecraft:redstone
# minecraft:snowball
# minecraft:oak_boat
# minecraft:milk_bucket
# minecraft:pufferfish_bucket
# minecraft:salmon_bucket
# minecraft:cod_bucket
# minecraft:tropical_fish_bucket
# minecraft:brick
# minecraft:clay_ball
# minecraft:sugar_cane
# minecraft:kelp
# minecraft:book
# minecraft:slime_ball
# minecraft:chest_minecart
# minecraft:furnace_minecart
# minecraft:egg
# minecraft:compass
# minecraft:fishing_rod
# minecraft:clock
# minecraft:glowstone_dust
# minecraft:cod
# minecraft:salmon
# minecraft:tropical_fish
# minecraft:pufferfish
# minecraft:cooked_cod
# minecraft:cooked_salmon
# minecraft:ink_sac
# minecraft:rose_red
# minecraft:cactus_green
# minecraft:cocoa_beans
# minecraft:lapis_lazuli
# minecraft:purple_dye
# minecraft:cyan_dye
# minecraft:light_gray_dye
# minecraft:gray_dye
# minecraft:pink_dye
# minecraft:lime_dye
# minecraft:dandelion_yellow
# minecraft:light_blue_dye
# minecraft:magenta_dye
# minecraft:orange_dye
# minecraft:bone_meal
# minecraft:bone
# minecraft:sugar
# minecraft:cookie
# minecraft:filled_map
# minecraft:shears
# minecraft:melon_slice
# minecraft:dried_kelp
# minecraft:pumpkin_seeds
# minecraft:melon_seeds
# minecraft:chicken
# minecraft:cooked_chicken
# minecraft:rotten_flesh
# minecraft:ender_pearl
# minecraft:blaze_rod
# minecraft:ghast_tear
# minecraft:gold_nugget
# minecraft:nether_wart
# minecraft:glass_bottle
# minecraft:spider_eye
# minecraft:fermented_spider_eye
# minecraft:blaze_powder
# minecraft:magma_cream
# minecraft:brewing_stand
# minecraft:cauldron
# minecraft:ender_eye
# minecraft:glistering_melon_slice
# minecraft:bat_spawn_egg
# minecraft:blaze_spawn_egg
# minecraft:cave_spider_spawn_egg
# minecraft:chicken_spawn_egg
# minecraft:cod_spawn_egg
# minecraft:cow_spawn_egg
# minecraft:creeper_spawn_egg
# minecraft:dolphin_spawn_egg
# minecraft:donkey_spawn_egg
# minecraft:drowned_spawn_egg
# minecraft:elder_guardian_spawn_egg
# minecraft:enderman_spawn_egg
# minecraft:endermite_spawn_egg
# minecraft:evoker_spawn_egg
# minecraft:ghast_spawn_egg
# minecraft:guardian_spawn_egg
# minecraft:horse_spawn_egg
# minecraft:husk_spawn_egg
# minecraft:llama_spawn_egg
# minecraft:magma_cube_spawn_egg
# minecraft:mooshroom_spawn_egg
# minecraft:mule_spawn_egg
# minecraft:ocelot_spawn_egg
# minecraft:parrot_spawn_egg
# minecraft:phantom_spawn_egg
# minecraft:pig_spawn_egg
# minecraft:polar_bear_spawn_egg
# minecraft:pufferfish_spawn_egg
# minecraft:rabbit_spawn_egg
# minecraft:salmon_spawn_egg
# minecraft:sheep_spawn_egg
# minecraft:shulker_spawn_egg
# minecraft:silverfish_spawn_egg
# minecraft:skeleton_spawn_egg
# minecraft:skeleton_horse_spawn_egg
# minecraft:slime_spawn_egg
# minecraft:spider_spawn_egg
# minecraft:squid_spawn_egg
# minecraft:stray_spawn_egg
# minecraft:tropical_fish_spawn_egg
# minecraft:turtle_spawn_egg
# minecraft:vex_spawn_egg
# minecraft:villager_spawn_egg
# minecraft:vindicator_spawn_egg
# minecraft:witch_spawn_egg
# minecraft:wither_skeleton_spawn_egg
# minecraft:wolf_spawn_egg
# minecraft:zombie_spawn_egg
# minecraft:zombie_horse_spawn_egg
# minecraft:zombie_pigman_spawn_egg
# minecraft:zombie_villager_spawn_egg
# minecraft:experience_bottle
# minecraft:fire_charge
# minecraft:writable_book
# minecraft:written_book
# minecraft:emerald
# minecraft:item_frame
# minecraft:flower_pot
# minecraft:carrot
# minecraft:potato
# minecraft:baked_potato
# minecraft:poisonous_potato
# minecraft:map
# minecraft:golden_carrot
# minecraft:carrot_on_a_stick
# minecraft:nether_star
# minecraft:pumpkin_pie
# minecraft:firework_rocket
# minecraft:firework_star
# minecraft:enchanted_book
# minecraft:nether_brick
# minecraft:quartz
# minecraft:tnt_minecart
# minecraft:hopper_minecart
# minecraft:prismarine_shard
# minecraft:prismarine_crystals
# minecraft:rabbit
# minecraft:cooked_rabbit
# minecraft:rabbit_stew
# minecraft:rabbit_foot
# minecraft:rabbit_hide
# minecraft:armor_stand
# minecraft:iron_horse_armor
# minecraft:golden_horse_armor
# minecraft:diamond_horse_armor
# minecraft:lead
# minecraft:name_tag
# minecraft:command_block_minecart
# minecraft:mutton
# minecraft:cooked_mutton
# minecraft:white_banner
# minecraft:orange_banner
# minecraft:magenta_banner
# minecraft:light_blue_banner
# minecraft:end_crystal
# minecraft:chorus_fruit
# minecraft:popped_chorus_fruit
# minecraft:beetroot
# minecraft:beetroot_seeds
# minecraft:beetroot_soup
# minecraft:dragon_breath
# minecraft:spectral_arrow
# minecraft:tipped_arrow
# minecraft:shield
# minecraft:elytra
# minecraft:spruce_boat
# minecraft:birch_boat
# minecraft:jungle_boat
# minecraft:acacia_boat
# minecraft:dark_oak_boat
# minecraft:totem_of_undying
# minecraft:shulker_shell
# minecraft:iron_nugget
# minecraft:knowledge_book
# minecraft:debug_stick
# minecraft:music_disc_13
# minecraft:music_disc_cat
# minecraft:music_disc_blocks
# minecraft:music_disc_chirp
# minecraft:music_disc_far
# minecraft:music_disc_mall
# minecraft:music_disc_mellohi
# minecraft:music_disc_stal
# minecraft:music_disc_strad
# minecraft:music_disc_ward
# minecraft:music_disc_11
# minecraft:music_disc_wait
# minecraft:trident
# minecraft:phantom_membrane
# minecraft:nautilus_shell
# minecraft:heart_of_the_sea
# minecraft:cat_spawn_egg
# minecraft:fox_spawn_egg
# minecraft:panda_spawn_egg
# minecraft:pillager_spawn_egg
# minecraft:ravager_spawn_egg
# minecraft:trader_llama_spawn_egg
# minecraft:wandering_trader_spawn_egg
# minecraft:leather_horse_armor
# minecraft:crossbow
# minecraft:suspicious_stew
# minecraft:flower_banner_pattern
# minecraft:creeper_banner_pattern
# minecraft:skull_banner_pattern
# minecraft:mojang_banner_pattern
# minecraft:globe_banner_pattern
# minecraft:sweet_berries
# minecraft:honeycomb
# minecraft:bee_nest
# minecraft:honey_bottle
# minecraft:hoglin_spawn_egg
# minecraft:piglin_spawn_egg
# minecraft:strider_spawn_egg
# minecraft:zoglin_spawn_egg
# minecraft:zombified_piglin_spawn_egg
# minecraft:warped_fungus_on_a_stick
# minecraft:music_disc_pigstep
# minecraft:piglin_banner_pattern
# minecraft:netherite_ingot
# minecraft:netherite_scrap
# minecraft:netherite_sword
# minecraft:netherite_shovel
# minecraft:netherite_pickaxe
# minecraft:netherite_axe
# minecraft:netherite_hoe
# minecraft:netherite_helmet
# minecraft:netherite_chestplate
# minecraft:netherite_leggings
# minecraft:netherite_boots